### ISSUE TITLE
Incorrect numbering in first row/column

### ISSUE THREAD

**Issue by kerryb** [kerryb/crossword-maker#3]
Cells in the first row are numbered even if they have a blocked cell immediately below them, and similarly for the first column.

**Comment by kerryb** [comment]
There will now be a short pause while I introduce some unit tests …

**Comment by atleastimtrying** [comment]
Jasmine? if so will you be using something like grunt to run them?

**Comment by kerryb** [comment]
On 24 May 2015 13:05, "Anders Fisher" <notifications@github.com> wrote:
>
> Jasmine? if so will you be using something like grunt to run them?

Thought maybe jest. And no, that seems like overkill at the moment.

**Comment by kerryb** [comment]
Fixed in 1b0a2d3.
